### ISSUE TITLE
Mocking from complexe links missing

### ISSUE THREAD

**Issue by UrielMhezzek** [aspnet/EntityFramework.Docs.de-de#15]
I Missed, how to Mock n:m or other complex links.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: c9696766-8f5f-f762-e4f1-1d403b0b3276
* Version Independent ID: a6df7c92-facc-8fd5-d8c6-ac3d2668d9e8
* Content: [Tests mit Ihren eigenen Testdoubles - EF6](https://docs.microsoft.com/de-de/ef/ef6/fundamentals/testing/writing-test-doubles#feedback)
* Content Source: [entity-framework/ef6/fundamentals/testing/writing-test-doubles.md](https://github.com/aspnet/EntityFramework.Docs.de-de/blob/live/entity-framework/ef6/fundamentals/testing/writing-test-doubles.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by srvbpigh** [comment]
Hello, @UrielMhezzek
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @UrielMhezzek 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @UrielMhezzek
 
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team
