### ISSUE TITLE
Der Begriff "Tasten" ist falsch

### ISSUE THREAD

**Issue by hcarsten** [aspnet/EntityFramework.Docs.de-de#16]
hier müsste Keys mit "Schlüssel" übersetzt werden und nicht mit "Tasten" !

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: d0a084df-15c4-ab25-26ca-83c8bdf6f026
* Version Independent ID: f1fba5b2-eb2e-da0a-fce0-d492855c1777
* Content: [Schlüssel-EF Core](https://docs.microsoft.com/de-de/ef/core/modeling/keys?tabs=data-annotations#feedback)
* Content Source: [entity-framework/core/modeling/keys.md](https://github.com/aspnet/EntityFramework.Docs.de-de/blob/live/entity-framework/core/modeling/keys.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by srvbpigh** [comment]
Hello, @hcarsten
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hallo @hcarsten:

Vielen Dank für Ihren Beitrag. 

Beiträge zu Übersetzungsproblemen in maschinell übersetzten Inhalten werden zurzeit nicht akzeptiert. 

Wir schätzen Ihr Feedback und Ihre Vorschläge zu von Menschen übersetzten Inhalten. Diese werden verwendet, um die Engines für maschinelle Übersetzung zu trainieren. Mit der Zeit verbessern Ihre Beiträge also die Qualität menschlicher und maschineller Übersetzungen. 

Anhand des ms.translationtype-Metadatenwerts im Header einer Inhaltsdatei können Sie zwischen menschlicher und maschineller Übersetzung unterscheiden. Dabei steht „HT“ für menschliche Übersetzung und „MT“ für maschinelle Übersetzung. 

Vielen Dank für Ihre Unterstützung! 

Microsoft DOCS Global Experience Team
